import scrapy


class NcbiSpiderItem(scrapy.Item):
    #_define_the_fields_for_your_item_here_like:
    #_name_=_scrapy.Field()
    name = scrapy.Field()
    Description = scrapy.Field()
    Organism_name = scrapy.Field()
    Taxonomy_check = scrapy.Field()
    Infraspecific_name = scrapy.Field()
    Isolate = scrapy.Field()
    BioSample = scrapy.Field()
    BioProject = scrapy.Field()
    Submitter = scrapy.Field()
    Date = scrapy.Field()
    Assembly_type = scrapy.Field()
    Assembly_level = scrapy.Field()
    Genome_representation = scrapy.Field()
    Excluded_from_RefSeq = scrapy.Field()
    GenBank_assembly_accession = scrapy.Field()
    RefSeq_category = scrapy.Field()
    RefSeq_assembly_accession = scrapy.Field()
    RefSeq_assembly_and_GenBank_assembly_identical = scrapy.Field()
    WGS_Project = scrapy.Field()
    Assembly_method = scrapy.Field()
    Expected_final_version = scrapy.Field()
    Genome_coverage = scrapy.Field()
    Sequencing_technology = scrapy.Field()
    Total_sequence_length = scrapy.Field()
    Total_ungapped_length = scrapy.Field()
    Total_number_of_chromosomes_and_plasmids = scrapy.Field()
    Gaps_between_scaffolds = scrapy.Field()
    Number_of_scaffolds = scrapy.Field()
    Scaffold_N50 = scrapy.Field()
    Scaffold_L50 = scrapy.Field()
    Number_of_contigs = scrapy.Field()
    Contig_N50 = scrapy.Field()
    Contig_L50 = scrapy.Field()
    Number_of_component_sequences = scrapy.Field()


class NcbiGlobalAssemblyDefinitionItem(scrapy.Item):
    name = scrapy.Field()
    Molecule_name = scrapy.Field()
    GenBank_sequence = scrapy.Field()
    RefSeq_sequence = scrapy.Field()


class NcbiBioSampleItem(scrapy.Item):
    name = scrapy.Field()
    Identifiers = scrapy.Field()
    Organism = scrapy.Field()
    BioProject = scrapy.Field()
    Submission = scrapy.Field()
    Accession = scrapy.Field()
    ID = scrapy.Field()
    strain = scrapy.Field()
    host = scrapy.Field()
    collection_by = scrapy.Field()
    geographic = scrapy.Field()
    sample_type = scrapy.Field()
    sample_name = scrapy.Field()
    biomaterial_provider = scrapy.Field()
    culture_collection = scrapy.Field()
    host_health_state = scrapy.Field()
    isolate = scrapy.Field()
    isolation_source = scrapy.Field()
    serovar = scrapy.Field()
    ENA_first_public = scrapy.Field()
    ENA_last_update = scrapy.Field()
    # !
    ENA_CHECKLIST = scrapy.Field()
    External_Id = scrapy.Field()
    INSDC_center_alias = scrapy.Field()
    INSDC_center_name = scrapy.Field()
    INSDC_first_public = scrapy.Field()
    INSDC_last_update = scrapy.Field()
    INSDC_status = scrapy.Field()
    Submitter_Id = scrapy.Field()
    geographic_location_region_and_locality = scrapy.Field()
    anonymized_name = scrapy.Field()
    common_name = scrapy.Field()
    # !
    supplier_name = scrapy.Field()
    type_material = scrapy.Field()
    ArrayExpress_SPECIES = scrapy.Field()
    subject_id = scrapy.Field()
    collection_date = scrapy.Field()
    geographic_location = scrapy.Field()
    latitude_and_longitude = scrapy.Field()
    host_age = scrapy.Field()
    host_sex = scrapy.Field()
    serotype = scrapy.Field()
    host_disease = scrapy.Field()
    host_disease_outcome = scrapy.Field()
    wgMLST_genogroup = scrapy.Field()
    MLST_Type = scrapy.Field()
    MLVA_Complex = scrapy.Field()
    MLVA_Type = scrapy.Field()
    Mec_gene = scrapy.Field()
    SCCmec_Type = scrapy.Field()
    # !
    cgMLST_Complex_type = scrapy.Field()
    Specimen = scrapy.Field()
    Specimen_class = scrapy.Field()
    Specimen_submitter = scrapy.Field()
    genotype = scrapy.Field()
    # !
    broad_scale_environmental_context = scrapy.Field()
    # !
    local_scale_environmental_context = scrapy.Field()
    environmental_medium = scrapy.Field()
    Environmental_sample = scrapy.Field()
    isolation_and_growth_condition = scrapy.Field()
    number_of_replicons1 = scrapy.Field()
    project_name = scrapy.Field()
    reference_for_biomaterial = scrapy.Field()
    # !
    locus_tag_prefix = scrapy.Field()
    # ！
    geographic_location_latitude = scrapy.Field()
    geographic_location_longitude = scrapy.Field()
    # !
    is_the_sequenced_pathogen_host_associated = scrapy.Field()
    isolation_source_host_associated = scrapy.Field()
    # !
    isolation_source_non_host_associated = scrapy.Field()
